# distance between the camera mount and the center of the gripper. All units in milimeter
mount_translation_x: 0.0
mount_translation_y: 77.37 # 59.37 + 18 (half of the back of realsense)
mount_translation_z: 10

d405_height: 23.03
d405_center2left: 10.0

w: 1280
h: 720
fl_x: 641.299
fl_y: 641.299
cx: 636.707
cy: 362.299
k1: 0.0
k2: 0.0
p1: 0.0
p2: 0.0
